name: k3s+crio on ubuntu22.04

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      RUNTIME: crio
    steps:
      - name: Add CRI-O's GPG key
        run: |
          curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | sudo gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
          curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04/Release.key | sudo gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
      - name: Add CRI-O repo
        run: |
          echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.23.list
      - name: Install CRI-O
        run: |
          sudo apt-get update
          sudo apt-get install -y cri-o cri-o-runc
      - name: Start & enable CRI-O service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start crio.service
